name: rps

services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - redis
    volumes:
      - ./server/:/usr/src/app
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - ./server/.env
    stdin_open: true
    tty: true
    # entrypoint: poetry run python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
    entrypoint: python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000

  redis:
    image: "redis:7.4-alpine"
    ports:
      - "6379:6379"

  front:
    container_name: client
    image: node:23
    command: sh -c "npm install && npm run dev"
    network_mode: host
    volumes:
      - ./client/:/usr/src/app
      # - /usr/src/app/node_modules
    working_dir: /usr/src/app
    user: ${USER_ID:-1000}
    stdin_open: true
    tty: true