# Generated by Django 5.2 on 2025-05-08 00:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_client_email'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Conta à Pagar'), (2, 'Conta à Receber')], default=1)),
                ('due_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.IntegerField(choices=[(1, 'Espécie'), (2, 'Débito'), (3, 'Crédito'), (4, 'PIX')], default=1)),
                ('payment_status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Pago'), (3, 'Vencido'), (4, 'Cancelado')], default=1)),
                ('payment_status_date', models.DateTimeField(null=True)),
                ('notes', models.TextField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
